version: '3'

services:
  stocks_selenium:
    build:
      context: ./dockerfiles/selenium
      dockerfile: Dockerfile
    container_name: stocks_selenium
    user: root # Run as root user to avoid permission issues
    tty: true # Keep the container running with an interactive shell
    stdin_open: true
    ports:
      - "8080:8080" # Map container port 8080 to host port 8080
      - "4444:4444" # Map container port 4444 to host port 4444
    volumes:
      - ./scripts:/scripts # Mount the local scripts directory into the container
    environment:
      - DEBIAN_FRONTEND=noninteractive
    restart: unless-stopped
  stocks_postgres:
    build:
      context: ./dockerfiles/postgres
      dockerfile: Dockerfile
    container_name: stocks_postgres
    environment:
      POSTGRES_USER: stocks_user
      POSTGRES_DB: stocks_db
    volumes:
      - stocks_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
  stocks_minio:
    image: minio/minio
    container_name: stocks_minio
    volumes:
      - stocks_minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    restart: unless-stopped

volumes:
  stocks_postgres_data:
  stocks_minio_data:
  scripts:
